name: CI - Run ML Model Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Set-up-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Run action/checkout@v3
      uses: actions/checkout@v4

    - name: Set up python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Check Env
      run: |
        python --version
        pip --version

    - name: Install Dependencies
      run: |
        pip install mlflow==3.8.0
        pip install numpy==1.26.4 pandas==2.2.2 scikit-learn==1.6.1 matplotlib==3.9.2

    - name: Run mlflow project
      working-directory: ./MLProject
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      working-directory: ./MLProject
      run: |
        ls mlruns/*/*/meta.yaml | head -n 1 | awk -F'/' '{print $3}' > latest_run_id.txt
        cat latest_run_id.txt

    - name: Install Python Dependencies
      run: |
        pip install docker

    - name: Upload to Google Drive
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns

    - name: Build Docker Model
      working-directory: ./MLProject
      run: |
        mlflow models build-docker \
          -m runs:/$(cat latest_run_id.txt)/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Image Docker
      run: |
        docker tag hilmyfahrizal/msml-mlflow-model:latest \
                   hilmyfahrizal/msml-mlflow-model:ci-latest

    - name: Push Docker Image
      run: |
        docker push hilmyfahrizal/msml-mlflow-model:latest
        docker push hilmyfahrizal/msml-mlflow-model:ci-latest

    - name: Push Log in Docker Hub
      run: echo "Docker image successfully pushed to Docker Hub"

    - name: Complete job
      run: echo "CI pipeline completed successfully"
